GET http://localhost:3001/api/recaps
###
GET http://localhost:3001/api/recaps/1
###
# Login
POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "playerone@gmail.com",
  "password": "password123"
}

###

## Checking if user is still logged-in.
GET http://localhost:3001/api/sessions/current

###

## Execute Log Out.
DELETE http://localhost:3001/api/sessions/current

###