# This suite is for all the REST call from a REGISTERED user
# Login with registered user | return 201(Created)
POST http://localhost:3001/api/sessions
content-type: application/json

{
  "username": "playerone@gmail.com",
  "password": "password123"
}
###
# get all recaps | return 200(OK)
GET http://localhost:3001/api/recaps
###
# get a public recap | return 200(OK)
GET http://localhost:3001/api/recaps/1
###
# get a private recap | return 200(OK)
GET http://localhost:3001/api/recaps/2
###
# get a wrong recap | return 404(OK)
GET http://localhost:3001/api/recaps/99
###
# get a list of recaps, public and private | return 200(OK)
GET http://localhost:3001/api/recaps/myrecaps
###

# set visibility of a recap to public | return 200(OK)
PATCH localhost:3001/api/recaps/2/visibility
content-type: application/json

{"visibility": "public"}
###
# set visibility of a recap to private | return 200(OK)
PATCH localhost:3001/api/recaps/2/visibility
content-type: application/json

{"visibility": "private"}
###
# get themes | return 200
GET http://localhost:3001/api/themes
###
# get backgrounds | return 200
GET http://localhost:3001/api/backgrounds?themeId=2
###
# get templates | return 200
GET http://localhost:3001/api/templates?themeId=2
###
# post a recap | return 201
POST http://localhost:3001/api/recaps
Content-Type: application/json

{
  "title": "My 2024 in Games",
  "theme_id": 2,
  "visibility": "public",
  "derived_from_recap_id": null,
  "pages": [
    {
      "page_index": 0,
      "background_id": 7,
      "texts": [
        { "slot_index": 0, "content": "It all started here" }
      ]
    },
    {
      "page_index": 1,
      "background_id": 8,
      "texts": [
        { "slot_index": 0, "content": "So many hours played" }
      ]
    },
    {
      "page_index": 2,
      "background_id": 9,
      "texts": [
        { "slot_index": 0, "content": "Game over" }
      ]
    }
  ]
}
###
# post a wrong recap | return 422
POST http://localhost:3001/api/recaps
Content-Type: application/json

{
  "title": "Broken recap",
  "pages": []
}
###
# Checking if user is still logged-in | return 200(OK)
GET http://localhost:3001/api/sessions/current
###
# Logout | return 200(OK)
DELETE http://localhost:3001/api/sessions/current
###